name: Haskell Templates CI

on:
  pull_request:
    branches:
      - master
    path:
      - ./haskell

jobs:
  cabal:
    uses: ./.github/workflows/haskell-cabal.yml
    with:
      working-directory: ./haskell
  nix:
    uses: ./.github/workflows/haskell-nix.yml
    with:
      working-directory: ./haskell
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
